p8105_hw2_jd3924
================
Jiahe Deng
2022-10-01

``` r
library(tidyr)
library(readxl)
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ dplyr   1.0.10
    ## ✔ tibble  3.1.8      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ✔ purrr   0.3.4      
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readr)
```

### Problem 1

Below we import and clean data from
`NYC_Transit_Subway_Entrance_And_Exit_Data.csv`. The process begins with
data import, updates variable names, and selects the columns that will
be used in later parts fo this problem. We update `entry` from `yes` /
`no` to a logical variable. As part of data import, we specify that
`Route` columns 8-11 should be character for consistency with 1-7.

``` r
trans_ent = 
  read_csv("NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
           col_types = cols(Route8 = "c", Route9 = "c",
                            Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

As it stands, these data are not “tidy”: route number should be a
variable, as should route. That is, to obtain a tidy dataset we would
need to convert `route` variables from wide to long format. This will be
useful when focusing on specific routes, but may not be necessary when
considering questions that focus on station-level variables.

The following code chunk selects station name and line, and then uses
`distinct()` to obtain all unique combinations. As a result, the number
of rows in this dataset is the number of unique stations.

``` r
trans_ent %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

The next code chunk is similar, but filters according to ADA compliance
as an initial step. This produces a dataframe in which the number of
rows is the number of ADA compliant stations.

``` r
trans_ent %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

To compute the proportion of station entrances / exits without vending
allow entrance, we first exclude station entrances that do not allow
vending. Then, we focus on the `entry` variable – this logical, so
taking the mean will produce the desired proportion (recall that R will
coerce logical to numeric in cases like this).

``` r
trans_ent %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

Lastly, we write a code chunk to identify stations that serve the A
train, and to assess how many of these are ADA compliant. As a first
step, we tidy the data as alluded to previously; that is, we convert
`route` from wide to long format. After this step, we can use tools from
previous parts of the question (filtering to focus on the A train, and
on ADA compliance; selecting and using `distinct` to obtain dataframes
with the required stations in rows).

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
trans_ent %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

### Problem 2

``` r
mr_trash_wheel = 
  read_excel("Trash Wheel Collection Data.xlsx", range=cell_cols("A:N")) %>%
  drop_na(Dumpster)
  integer <- as.integer(mr_trash_wheel$`Sports Balls`)
  mutate(mr_trash_wheel,revised_sport_balls = integer)
```

    ## # A tibble: 547 × 15
    ##    Dumpster Month Year  Date                Weight (to…¹ Volum…² Plast…³ Polys…⁴
    ##       <dbl> <chr> <chr> <dttm>                     <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00         4.31      18    1450    1820
    ##  2        2 May   2014  2014-05-16 00:00:00         2.74      13    1120    1030
    ##  3        3 May   2014  2014-05-16 00:00:00         3.45      15    2450    3100
    ##  4        4 May   2014  2014-05-17 00:00:00         3.1       15    2380    2730
    ##  5        5 May   2014  2014-05-17 00:00:00         4.06      18     980     870
    ##  6        6 May   2014  2014-05-20 00:00:00         2.71      13    1430    2140
    ##  7        7 May   2014  2014-05-21 00:00:00         1.91       8     910    1090
    ##  8        8 May   2014  2014-05-28 00:00:00         3.7       16    3580    4310
    ##  9        9 June  2014  2014-06-05 00:00:00         2.52      14    2400    2790
    ## 10       10 June  2014  2014-06-11 00:00:00         3.76      18    1340    1730
    ## # … with 537 more rows, 7 more variables: `Cigarette Butts` <dbl>,
    ## #   `Glass Bottles` <dbl>, `Grocery Bags` <dbl>, `Chip Bags` <dbl>,
    ## #   `Sports Balls` <dbl>, `Homes Powered*` <dbl>, revised_sport_balls <int>,
    ## #   and abbreviated variable names ¹​`Weight (tons)`, ²​`Volume (cubic yards)`,
    ## #   ³​`Plastic Bottles`, ⁴​Polystyrene

``` r
sum(as.integer(mr_trash_wheel$`Sports Balls`))
```

    ## [1] 6869

In mr_trash_wheel dataset, there was 547 observation and 15 variables. I
round the number of sports balls to the nearest integer, and name the
variable as revised_sport_balls.

``` r
pro_trash_wheel = 
  read_excel("Trash Wheel Collection Data.xlsx",sheet = 2) %>%
  drop_na(Dumpster)
pro_trash_wheel
```

    ## # A tibble: 94 × 13
    ##    Dumpster Month     Year Date                Weight …¹ Volum…² Plast…³ Polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 84 more rows, 5 more variables: `Cigarette Butts` <dbl>,
    ## #   `Glass Bottles` <dbl>, `Grocery Bags` <dbl>, `Chip Bags` <dbl>,
    ## #   `Homes Powered*` <dbl>, and abbreviated variable names ¹​`Weight (tons)`,
    ## #   ²​`Volume (cubic yards)`, ³​`Plastic Bottles`, ⁴​Polystyrene

``` r
sum(pro_trash_wheel$`Weight (tons)`)
```

    ## [1] 190.12

In Pro_trash_Wheel, there are 822 observation and 9 variable. the total
weight of trash collected by Professor Trash Wheel is 190.12 tons.
